### ISSUE TITLE
Adaway

### ISSUE THREAD

**Issue by selcukXIII** [CoskunZ/adblock-turkish#1]
Android telefonumda Adaway programı ile senin host dosyalarını kullanmayı denedim ama hostlara ulaşamadı, programda sıkıntı yok başka hostlarda bir sıkıntı olmadı. Acaba github domaini yüzünden mi oldu bir fikrin var mı?

**Comment by CoskunZ** [comment]
@Yudmud 
Ben host dosyası değil, engelleme filtresi üstünde çalışıyorum. Yani sadece engelleme uygulamaları anlayabilir. uBlock Origin gibi.
Adaway ise host dosyaları kabul eder, http://someonewhocares.org/hosts/hosts gibi.
